resources:
      
  - name: myRepo
    type: GitRepo
    configuration:
      gitProvider: jatin_gh
      path: jatindogra/powershell

pipelines:

  - name: jatin_pipeline
    steps:  
      - name: functions
        type: PowerShell
        configuration:         
          inputResources:
            - name: myRepo

        execution:
          onExecute:
            - echo "hello"        
            
      - name: functions2
        type: PowerShell
        configuration:          
          inputSteps:
            - name: functions
        execution:
          onExecute:
            - get-childitem $res_myRepo_resourcePath    
            - restore_run_files -name repo_pipe -path $step_tmp_dir   
            - get-childitem $res_myRepo_resourcePath    
            - echo $pipelineVariable                        
            - echo $runVariable       
            
      - name: functions3
        type: PowerShell
        configuration:         
          inputSteps:
            - name: functions2
        execution:
          onExecute:
            - get-childitem $res_myRepo_resourcePath    
            - echo $pipelineVariable                       
            - restore_pipeline_files -name vijay -path $step_tmp_dir
            - get-childitem $step_tmp_dir   
            - echo $runVariable            
            

            
